version: '3'

services:
  web:
    image: jekyll/jekyll:pages
    # --force_polling necessary on Windows
    entrypoint: ["jekyll"]
    command: ["serve", "--watch", "--livereload", "--force_polling" ]
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll